TARGET_PS2TOOLCHAIN_IOP=iop

IOP_MAKE_PATH := $(PS2TOOLCHAIN)/$(TARGET_PS2TOOLCHAIN_IOP)
IOP_INCLUDE_PATH := makefiles/$(IOP_MAKE_PATH)/$(TARGET_PS2TOOLCHAIN_IOP)

IOP_COMPILE_TARGETS += "mipsel-ps2-irx"
IOP_COMPILE_TARGETS += "mipsel-ps2-elf"

# MAKE TARGETS
IOP_MAKE_TARGET := $(PS2TOOLCHAIN)-$(TARGET_PS2TOOLCHAIN_IOP)
IOP_MAKE_TARGET_BINUTILS := $(PS2TOOLCHAIN_HIDE_SUBCOMPILER_TARGETS)$(IOP_MAKE_TARGET)-binutils
IOP_MAKE_TARGET_GCC_STAGE1 := $(PS2TOOLCHAIN_HIDE_SUBCOMPILER_TARGETS)$(IOP_MAKE_TARGET)-gcc-stage1

# DIRECTORIES FOR TARGETS
IOP_DIR_TARGET_BINUTILS := $(IOP_MAKE_PATH)/binutils
IOP_DIR_TARGET_GCC_STAGE1 := $(IOP_MAKE_PATH)/gcc-stage1

# MAKE DEPS
IOP_DEPS += .depends
IOP_DEPS += $(IOP_MAKE_TARGET_BINUTILS)
IOP_DEPS += $(IOP_MAKE_TARGET_GCC_STAGE1)

include $(IOP_INCLUDE_PATH)-binutils.mk
include $(IOP_INCLUDE_PATH)-gcc-stage1.mk

$(PS2TOOLCHAIN_HIDE_COMPILER_TARGETS)$(IOP_MAKE_TARGET): $(IOP_DEPS)

am_$(PS2TOOLCHAIN)_targets += $(PS2TOOLCHAIN_HIDE_COMPILER_TARGETS)$(IOP_MAKE_TARGET)
