TARGET_PS2TOOLCHAIN_DVP=dvp

DVP_MAKE_PATH = $(PS2TOOLCHAIN)/$(TARGET_PS2TOOLCHAIN_DVP)
DVP_INCLUDE_PATH = makefiles/$(DVP_MAKE_PATH)/$(TARGET_PS2TOOLCHAIN_DVP)

DVP_COMPILE_TARGETS += "dvp"

# MAKE TARGETS
DVP_MAKE_TARGET := $(PS2TOOLCHAIN)-$(TARGET_PS2TOOLCHAIN_DVP)
DVP_MAKE_TARGET_BINUTILS := $(PS2TOOLCHAIN_HIDE_SUBCOMPILER_TARGETS)$(DVP_MAKE_TARGET)-binutils

# DIRECTORIES FOR TARGETS
DVP_DIR_TARGET_BINUTILS := $(DVP_MAKE_PATH)/binutils

# MAKE DEPS
DVP_DEPS += .depends
DVP_DEPS += $(DVP_MAKE_TARGET_BINUTILS)


include $(DVP_INCLUDE_PATH)-binutils.mk

$(PS2TOOLCHAIN_HIDE_COMPILER_TARGETS)$(DVP_MAKE_TARGET): $(DVP_DEPS)

am_$(PS2TOOLCHAIN)_targets += $(PS2TOOLCHAIN_HIDE_COMPILER_TARGETS)$(DVP_MAKE_TARGET)
